function mesh2raw(X,F, fn)
%%% save the coordinates of the faces as a raw text file with nx9 rows
fid = fopen(fn, 'w');
for ix = 1:size(F,1),   % loop over the faces
    fprintf(fid, '%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\n',...
        X(F(ix,1),1),X(F(ix,1),2),X(F(ix,1),3),...
        X(F(ix,2),1),X(F(ix,2),2),X(F(ix,2),3),...
        X(F(ix,3),1),X(F(ix,3),2),X(F(ix,3),3)...
        );
end
fclose(fid);